add option to configure a base path
artemeon/composer-merge-plugin pull request #2
Opened 2021-09-13 16:51 UTC by chriskapp

2021-10-01 12:47 UTC, MikeMarschall requested changes

2021-10-01 12:47 UTC, MikeMarschall commented on src/Plugin/MergePlugin.php
> +        if ($packageConfig) {
```suggestion
        if ($composer->getPackage()->getExtra()['packageconfig'] ?? true) {
```

2021-10-01 12:47 UTC, MikeMarschall commented on src/Plugin/MergePlugin.php
> +        if ($overrides) {
```suggestion
        if ($rootPackage->getExtra()['overrides'] ?? true) {
```
die lokale Variable hier und in Zeile 44 wird nur jeweils genau einmal benutzt, ich würde sie inlinen

2021-10-01 12:47 UTC, MikeMarschall commented on src/Plugin/MergePlugin.php
> +        }
```suggestion
        if (empty($basePath) || !is_dir($basePath)) {
            return self::MODULES_BASE_PATH;
        }

        return $basePath;
```
und noch ein `use function dir` 🙂

2022-03-04 10:13 UTC, sidler approved these changes

2022-03-04 10:13 UTC, marcreichel approved these changes

2022-03-04 10:14 UTC, merged